apiVersion: v1
kind: Service
metadata:
  name: order-management-service
  labels:
    app: order-management-service
spec:
  selector:
    app: order-management-service
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
  type: ClusterIP
