apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
  labels:
    app: product-catalog-service
spec:
  selector:
    app: product-catalog-service
  ports:
  - port: 3005
    targetPort: 3005
    protocol: TCP
  type: ClusterIP
