apiVersion: v1
kind: Service
metadata:
  name: demand-forecasting-service
  labels:
    app: demand-forecasting-service
spec:
  selector:
    app: demand-forecasting-service
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
  type: ClusterIP
